common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ea_db2
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: 123
  application:
    name: cs544-202403-project

logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs
