common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
    user:
      name: user
      password: 123
  application:
    name: Attendance
  spring:
    datasource:
      url: jdbc:h2:mem:testdb
      username: SA
      password: password
      driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/cs544-labs
#    username: root
#    password: 123456
#    driverClassName: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs