common:
  security:
    enabled: false
  feign-oauth:
    enabled: true
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
#  security:
#    user:
#      name: user
#      password: 123
  application:
    name: Attendance
  datasource:
    url: jdbc:postgresql://localhost:5432/NEW
    username: postgres
    password: A123@123h
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs